<h2>CSCI 4270/6270<br>Computational Vision<br>Prof. Chuck Stewart</h2>
<h3>Lecture 01 --- Introduction to NumPy<br>January 9, 2024</h3>

### NumPy: Numerical Python

Array programming.
+ Compact (few for loops)
+ Clear
+ Powerful
+ Efficient - speeds nearing those of compiled languages

Upshot:
+ You must learn to be proficient at array programming


See, for example: 
+ Charles R. Harris et al., Array Programming with NumPy, *Nature*, volume 585, pages 357–362(2020)

Images are large three dimensional arrays
+ IPhone 15 default setting is : 6000 x 4000 x 3
+ Typically we will work with reduced resolution images


### Overview of the Basics

Here is an outline of the topics we will cover in class.  What we write to fill in will be posted both as an html file and as a Jupyter notebook.
+ A first example
+ Array creation
+ Array dimensions
+ Changing shape
+ Indexing and slicing
+ Views and copying
+ Arithmetic operators
+ Universal functions
+ Concatenating and splitting
+ Summary of differences between NumPy arrays and Python lists

See the Submitty page for links to on-line tutorials

### A first example
We'll start with an example showing
+ Initial creation
+ Reshaping from one dimension to two
+ Indexing to access and change values
+ Single data type:  dtype
+ The type of the array object

In [1]:
import numpy as np
# We'll look at creating an array from a python list, printing its shape, and making shallow copies
v = [1, 5, 3, 7, 9, 4]
a = np.array(v)
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
b = a.reshape(2, 3)
print(b)
print(b.shape)
b[0,1] = 99
print(b)
print('a =', a)
print('v =', v)

[1 5 3 7 9 4]
<class 'numpy.ndarray'>
int64
(6,)
[[1 5 3]
 [7 9 4]]
(2, 3)
[[ 1 99  3]
 [ 7  9  4]]
a = [ 1 99  3  7  9  4]
v = [1, 5, 3, 7, 9, 4]


### Array creation
Many methods to explore:
+ Creating directly from a list or from lists of lists
+ arange
+ linspace
+ random
+ eye
+ ones
+ zeros
+ setting the data type


In [2]:
# Array creation examples, starting with np.arange() and demoing reshape
a = np.arange(48)
print(a)
b = a.reshape(2, 3, 8)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]
  [16 17 18 19 20 21 22 23]]

 [[24 25 26 27 28 29 30 31]
  [32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47]]]


In [4]:
# linspace (linear space); endpoints are included by default
c = np.linspace(0, 1, 11)
print(c)

d = np.linspace(0, 1, 10, endpoint=False)
print(d)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [5]:
# np.random.random (uniform float in [0,1]) and np.random.randint (uniform in the specified range
# both require shape tuples)
a = np.random.random(15)
print(a)
b = np.random.randint(10, 20, (6,3))
print(b)

[0.67610593 0.81429644 0.112854   0.04853811 0.13835661 0.80540944
 0.74793372 0.19980743 0.37639499 0.13000692 0.69726534 0.55321366
 0.52779192 0.26351685 0.12364182]
[[13 12 19]
 [13 19 11]
 [12 19 10]
 [11 18 10]
 [13 19 11]
 [17 16 16]]


In [6]:
# np.eye gives an identity matrix, and you can optionally 
# choose the diagoanl with optional k parameter
np.eye(4, 5, k=-1)


array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [12]:
# np.ones and np.zeros
a = np.zeros((6, 4), dtype=np.int32)
print(a.dtype)

int32


### Array dimensions
+ 1-d: a row vector
+ 2-d: a traditional array with rows indexed first and columns indexed second
+ n-d: nested dimensions read from outside in
+ Can even have 0-d, which is essentially a scalar, but we will not spend any time on this



In [13]:
# We'll focus on 3d 
print(np.arange(48).reshape((2,3,8)))


[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]
  [16 17 18 19 20 21 22 23]]

 [[24 25 26 27 28 29 30 31]
  [32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47]]]


### Shapes and reshaping
+ We can reshape a NumPy array to any other shape that uses the same number of values
+ The shape may be assigned as an l-value and accessed as an r-value
    + It is simply an attribute of each NumPy array
+ ravel and flatten create 1d versions of arrays
    + ravel creates a shallow copy, while flatten creates a deep copy.

In [16]:
# Examples of shape and reshaping, including ravel and flatten 
# (note the aliasing)
v = [4, 19, 12, 93, 45, 16]
a = np.array(v)
a.shape = (2,3)
print(a)
u = a.ravel()
print(u)




[[ 4 19 12]
 [93 45 16]]
[ 4 19 12 93 45 16]


### Indexing and slicing
+ Initial intuitions are similar to operations on Python lists
    + Watch out though for important differences that will emerge, starting with syntax
+ 1d, 2d, and more
+ Leaving out a dimension (at the end) gives the entire contents of that dimension

In [17]:
# Examples of indexing and slicing
# 1. 2d array, 2d subarray, 1d subarray
a = np.arange(20).reshape((4,5))
print(a)
b = a[2:4, 1:3]
print(b)
a[0]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[11 12]
 [16 17]]


array([0, 1, 2, 3, 4])

In [20]:
# 2. 3d example down to 2d
a = np.random.randint(0, 20, (2,3,4))
print(a)
print()
print(a[1])
print()
print(a[1,1])

[[[ 0 13  1  4]
  [17 16 16 16]
  [13 12 17 16]]

 [[17  4 14 13]
  [ 3  9  1  1]
  [13 19 18  4]]]

[[17  4 14 13]
 [ 3  9  1  1]
 [13 19 18  4]]

[3 9 1 1]


In [22]:
print(a[1,1])
print()
print(a[0, 1:, 1:])

[3 9 1 1]

[[16 16 16]
 [12 17 16]]


### Views and copying
+ Unlike lists, when an array is sliced, the result is a view or shallow copy of the array.
+ When the slice is an l-value, the contents of the array are changed!
    + We will use this soon to insert a picture within a picture

In [28]:
# Examples for views and copying
# 1. 2d array with subarray assigned to a constant
a = np.arange(15).reshape(3,5)
print(a)
print()
b = a[1:, 2:4]
print(b)
b[:,:] = 99
print(b)
print()
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 7  8]
 [12 13]]
[[99 99]
 [99 99]]

[[ 0  1  2  3  4]
 [ 5  6 99 99  9]
 [10 11 99 99 14]]


In [29]:
b = 789
print(b)
print()
print(a)

789

[[ 0  1  2  3  4]
 [ 5  6 99 99  9]
 [10 11 99 99 14]]


In [31]:
# 2. 2d array with subarray assigned from another array
b = np.zeros((3,4))
print(b)
c = np.random.randint(-100, -90, b.shape)
print("c", c)
b[:, :] = c[:, :]     # copy all of c into all of b
print('b', b)
b[0,0] = 333
print('c[0,0]', c[0,0])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
c [[ -94  -93 -100 -100]
 [ -99  -92  -91 -100]
 [ -94 -100  -91  -94]]
b [[ -94.  -93. -100. -100.]
 [ -99.  -92.  -91. -100.]
 [ -94. -100.  -91.  -94.]]
c[0,0] -94


In [ ]:
# 4. types and d-types
print(a.dtype)
print(type(a))

### Arithmetic operators applied to arrays
+ Addition, subtraction, multiplication, etc.
    + Note that multiplication is component-wise, rather than standard matrix multiplication
    + Achieve matrix multiplication with 'dot' method
+ Operators require compatible dimensions.  For example
    + A scalar is compatible with any array
    + Arrays of the same dimensions are compatible 
+ A vector and a 2d array may be added if the array has the same number of columns as the length of the vector.
    + This is an initial example of NumPy "broadcast rules", which we will study in more detail in Lecture 2

In [32]:
# 1. Addition, subtraction, component-wise multiplication
a = np.arange(10).reshape(2,5)
b = np.random.randint(0,100, (2,5))
print('a', a)
print('b', b)
print('a+b', a+b)
print('a-b', a-b)
print('a*b', a*b)


a [[0 1 2 3 4]
 [5 6 7 8 9]]
b [[21 41 53 46 42]
 [69  9 68 60  4]]
a+b [[21 42 55 49 46]
 [74 15 75 68 13]]
a-b [[-21 -40 -51 -43 -38]
 [-64  -3 -61 -52   5]]
a*b [[  0  41 106 138 168]
 [345  54 476 480  36]]


In [35]:
# 2. Matrix multiplication as a dot product
print(np.dot(a, b.T))  # 2x5 times 5x2 -> 2x2
print(a @ b.T)
print()
print(b.T @ a)

[[ 453  341]
 [1468 1391]]
[[ 453  341]
 [1468 1391]]

[[345 435 525 615 705]
 [ 45  95 145 195 245]
 [340 461 582 703 824]
 [300 406 512 618 724]
 [ 20  66 112 158 204]]


In [40]:
c = np.arange(24).reshape(2,3,4)
print(c)
print()
print(np.transpose(c, (0, 2, 1)))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


In [43]:
# 3. Vector added to 2d array
a = np.arange(5)
b = np.arange(15).reshape(3, 5)
print(a)
print()
print(b)
print()
print(a+b)

[0 1 2 3 4]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  2  4  6  8]
 [ 5  7  9 11 13]
 [10 12 14 16 18]]


### Universal functions - Applied to entire array
+ We'll look at just a few important examples (of many):
    + Average, dot, max, sum, cumsum
+ Can specify the axis along which the function is applied
+ Some functions, like argmax, give results that are defined in terms of the 1d, raveled version of the array!

In [57]:
# Universal function examples
# 1. Max, average, sum
b = np.random.randint(0, 100, (3, 5))
print(b)



[[ 0 10 15 93 80]
 [32  0 42 23 98]
 [ 2 67 55  6 73]]


In [58]:
print('max of b', np.max(b))
print('sum of b', np.sum(b))
print('avg of b', np.average(b))

max of b 98
sum of b 596
avg of b 39.733333333333334


In [59]:
# 2. Operations applied along an axis, e.g. max in each row
print(np.max(b, axis=0))
print(np.max(b, axis=1))

[32 67 55 93 98]
[93 98 73]


In [60]:
# 3. Cumulative summations along an axis
# As above...
print(b)
print(np.cumsum(b))


[[ 0 10 15 93 80]
 [32  0 42 23 98]
 [ 2 67 55  6 73]]
[  0  10  25 118 198 230 230 272 295 393 395 462 517 523 596]


In [61]:
# 4. Cumulative summation and ravel and reshape
print(np.cumsum(b).reshape(b.shape))


[[  0  10  25 118 198]
 [230 230 272 295 393]
 [395 462 517 523 596]]


In [65]:
# 5. Use of unravel_index tells where i-th entry will be in an array
#. Goal:  what are the indices of the max value of a?
print(b)
print(np.max(b))

print(np.ravel(b))

print(np.argmax(b))  # gives it in unraveled version
i = np.argmax(b)
print(np.unravel_index(i, b.shape))   # interpret i in the shape of b



[[ 0 10 15 93 80]
 [32  0 42 23 98]
 [ 2 67 55  6 73]]
98
[ 0 10 15 93 80 32  0 42 23 98  2 67 55  6 73]
9
(1, 4)


### Combining and splitting arrays
+ concatenate:
    + Give tuple of arrays and specify axis along which to combine
    + Arrays dimensions must match exactly except along the axis
+ Split using indices
+ We'll look at example of combining 2d arrays into another 2d array, but also extending to 3d using the stack method
    + Useful for splitting and combining images

In [75]:
# Concatenate two dimensional arrays
a = np.arange(10).reshape(2,5)
b = np.arange(90,100).reshape(2,5)
print(a)
print(b)
print()
print(np.concatenate((a,b), axis=0))  # stack them up
print(np.concatenate((a,b), axis=1))  # iterate in column index
c = np.arange(20).reshape(2,10)
d = np.concatenate((a,c), axis=1)   # only have to be the same shape along the axis
print(d)
# print(np.concatenate((a,c), axis=0))


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[90 91 92 93 94]
 [95 96 97 98 99]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [90 91 92 93 94]
 [95 96 97 98 99]]
[[ 0  1  2  3  4 90 91 92 93 94]
 [ 5  6  7  8  9 95 96 97 98 99]]
[[ 0  1  2  3  4  0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]


In [72]:
# Split the result - split returns a Python list of NumPy arrays
v = np.split(d, (4, 11, 13), axis=1)   # python array with 4 NumPy arrays
print(d)
print(len(v))
print('split 0\n', v[0])
print('split 1\n', v[1])

[[ 0  1  2  3  4  0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
4
split 0
 [[0 1 2 3]
 [5 6 7 8]]
split 1
 [[ 4  0  1  2  3  4  5]
 [ 9 10 11 12 13 14 15]]


In [ ]:
# Stack


In [74]:
# Tile
a = np.arange(6).reshape(2,3)
print(a)
np.tile(a, (4, 2))

[[0 1 2]
 [3 4 5]]


array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### NumPy arrays vs. Python lists, revisited
+ NumPy arrays are homogeneous; Python lists are heterogeneous
+ Slicing a NumPy array creates a view without copying; slicing a Python list creates a new list
+ Many functional and numeric operations have been created for NumPy arrays